[package]
name = "rusty_chain"
version = "0.1.0"
authors = ["Collin Jones <cjones28@luc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name= "rustychainlib"
psth= "src/lib.rs"
[dependencies]
hex = "0.4.0"